from fastapi import FastAPI, HTTPException
import yfinance as yf
import pandas as pd
import numpy as np
import feedparser
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

# Tech Analysis Imports
from ta.trend import SMAIndicator, MACD, ADXIndicator
from ta.momentum import RSIIndicator
from ta.volatility import AverageTrueRange, BollingerBands

# Machine Learning Imports
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_score

app = FastAPI()
analyzer = SentimentIntensityAnalyzer()

# --- HELPER FUNCTIONS ---

def get_clean_name(ticker_obj, symbol):
    try:
        full_name = ticker_obj.info.get('longName', symbol)
        return full_name.replace("Limited", "").replace("Ltd", "").replace("Inc", "").strip()
    except:
        return symbol

def get_stock_news(query_name):
    encoded_name = query_name.replace(" ", "+")
    rss_url = f"https://news.google.com/rss/search?q={encoded_name}+stock+news&hl=en-IN&gl=IN&ceid=IN:en"
    feed = feedparser.parse(rss_url)
    return [{"title": x.title, "link": x.link, "published": x.published} for x in feed.entries[:3]]

def get_sentiment_score(news_items):
    if not news_items: return 0
    scores = [analyzer.polarity_scores(item['title'])['compound'] for item in news_items]
    return sum(scores) / len(scores)

# --- THE ML ENGINE ---

def train_and_predict(df):
    """
    Trains a Random Forest model on the past 1 year of data 
    to predict if Tomorrow's Close > Today's Close.
    """
    data = df.copy()
    
    # 1. Feature Engineering (The "Inputs" for the AI)
    # We teach the model relationships, not just raw prices
    data['RSI'] = RSIIndicator(close=data['Close'], window=14).rsi()
    data['MACD'] = MACD(close=data['Close']).macd_diff() # Histogram usually captures momentum better
    data['SMA_200'] = SMAIndicator(close=data['Close'], window=200).sma_indicator()
    data['SMA_50'] = SMAIndicator(close=data['Close'], window=50).sma_indicator()
    
    # Ratios (better than raw price)
    data['SMA_Ratio'] = data['SMA_50'] / data['SMA_200']
    data['Close_to_SMA200'] = data['Close'] / data['SMA_200']
    data['RSI_Lag1'] = data['RSI'].shift(1) # What was RSI yesterday?
    
    # Create Target: 1 if Tomorrow Close > Today Close, else 0
    data['Target'] = (data['Close'].shift(-1) > data['Close']).astype(int)
    
    # Drop NaN values generated by indicators/shifting
    data = data.dropna()
    
    # Define features to use
    features = ['RSI', 'MACD', 'SMA_Ratio', 'Close_to_SMA200', 'RSI_Lag1']
    
    # Split Data (Last 100 days for validation, rest for training)
    # Note: In real life, we'd use TimeSeriesSplit, but this is simple/fast
    X = data[features]
    y = data['Target']
    
    # We train on ALL past data except the very last row (which has no target yet)
    # Then we predict the probability for the VERY last row (Today)
    
    model = RandomForestClassifier(n_estimators=100, min_samples_split=10, random_state=1)
    
    # Train on everything up to yesterday
    model.fit(X.iloc[:-1], y.iloc[:-1])
    
    # Predict for Today (The last row)
    prediction_prob = model.predict_proba(X.iloc[[-1]])[0][1] # Probability of Class 1 (Up)
    
    return round(prediction_prob * 100, 1) # Return percentage (e.g., 65.5%)

# --- API ENDPOINTS ---

@app.get("/analyze/{symbol}")
def analyze_stock(symbol: str):
    try:
        ticker = yf.Ticker(symbol)
        company_name = get_clean_name(ticker, symbol)
        
        # Get 2 years of data (needed for reliable 200 SMA + ML Training)
        df = ticker.history(period="2y")
        
        if df.empty:
            raise HTTPException(status_code=404, detail="No data found")

        # 1. Run the Machine Learning Model
        ml_confidence = train_and_predict(df)
        
        # 2. Traditional Technical Indicators (for display)
        latest = df.iloc[-1]
        current_price = latest['Close']
        atr = AverageTrueRange(high=df["High"], low=df["Low"], close=df["Close"], window=14).average_true_range().iloc[-1]
        rsi = RSIIndicator(close=df["Close"], window=14).rsi().iloc[-1]
        
        # 3. NLP Sentiment
        news = get_stock_news(company_name)
        sentiment_score = get_sentiment_score(news)
        
        # 4. Synthesize the Signal
        # We combine ML Probability + News Sentiment
        
        final_score = ml_confidence # Start with ML probability (0-100)
        
        # Adjust based on News (News can swing score by +/- 10%)
        if sentiment_score > 0.2: final_score += 10
        if sentiment_score < -0.2: final_score -= 10
        
        # Cap score
        final_score = max(0, min(100, final_score))
        
        signal = "HOLD"
        if final_score > 65: signal = "BUY"
        if final_score < 35: signal = "SELL"
        
        return {
            "symbol": symbol.upper(),
            "company_name": company_name,
            "current_price": round(current_price, 2),
            "ml_prediction": {
                "direction_probability": f"{ml_confidence}% chance of Price UP",
                "model_type": "Random Forest Classifier (100 Trees)",
                "features_used": ["RSI", "MACD", "SMA_Ratio", "Lagged_RSI"]
            },
            "news_sentiment": {
                "score": round(sentiment_score, 2),
                "impact": "Positive" if sentiment_score > 0 else "Negative"
            },
            "final_verdict": {
                "score": round(final_score, 1),
                "signal": signal,
                "stop_loss": round(current_price - (2*atr), 2),
                "target": round(current_price + (3*atr), 2) # Risk 1 : Reward 1.5
            },
            "latest_news": news
        }

    except Exception as e:
        print(e)
        raise HTTPException(status_code=500, detail=str(e))